import os
from typing import List, Optional
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from pydantic import BaseModel, Field
import google.generativeai as genai

app = FastAPI(title="EndoTrack API", version="2.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)

# --- Schemas ---
class SymptomEntry(BaseModel):
    date: str
    cycle_day: int
    pain_level: int = Field(..., ge=1, le=10)
    primary_location: str
    gi_distress: bool
    fatigue_level: int = Field(..., ge=1, le=10)
    notes: Optional[str] = ""

class SummaryRequest(BaseModel):
    patient_id: str
    entries: List[SymptomEntry]

class QARequest(BaseModel):
    question: str

db_symptom_logs = []

# --- API Endpoints ---
@app.get("/api/health")
def health_check():
    return {"status": "online", "service": "EndoTrack Backend", "version": "2.0.0"}

@app.post("/api/symptoms")
def create_symptom_log(entry: SymptomEntry):
    db_symptom_logs.append(entry.model_dump())
    return {"status": "success", "message": "Log saved", "total_logs": len(db_symptom_logs)}

@app.get("/api/symptoms")
def get_symptom_logs():
    return {"status": "success", "data": db_symptom_logs}

@app.post("/api/generate-summary")
def generate_doctor_summary(payload: SummaryRequest):
    if not GEMINI_API_KEY:
        raise HTTPException(status_code=500, detail="Gemini API Key is missing.")
    if not payload.entries:
        raise HTTPException(status_code=400, detail="No symptom logs provided.")

    logs_text = "\n".join([
        f"- Date: {e.date} (Day {e.cycle_day}): Pain {e.pain_level}/10 [{e.primary_location}], GI: {e.gi_distress}, Fatigue: {e.fatigue_level}/10. Notes: '{e.notes}'"
        for e in payload.entries
    ])

    prompt = f"""
    You are an AI clinical assistant helping synthesize patient symptom history for a gynecologist appointment.
    Analyze the following patient logs and produce a 'Doctor Consultation Brief':

    Structure into 3 key sections:
    1. Pain Patterns & Peak Cycles
    2. Gastrointestinal & Systemic Indicators
    3. Clinical Discussion Key Points

    Patient Symptom History:
    {logs_text}

    MANDATORY DISCLAIMER: End with a statement that this summary is a tracking tool and not a diagnosis.
    """

    try:
        model = genai.GenerativeModel("gemini-3.5-flash")
        response = model.generate_content(prompt)
        return {"status": "success", "summary": response.text}
    except Exception as err:
        raise HTTPException(status_code=500, detail=f"AI Service Error: {str(err)}")

@app.post("/api/chat-qa")
def educational_qa(req: QARequest):
    if not GEMINI_API_KEY:
        raise HTTPException(status_code=500, detail="Gemini API Key is missing.")

    system_instruction = (
        "You are an empathetic medical educator specializing in endometriosis. "
        "Answer patient questions using evidence-based information and emphasize that you cannot diagnose."
    )

    try:
        model = genai.GenerativeModel("gemini-3.5-flash", system_instruction=system_instruction)
        response = model.generate_content(req.question)
        return {"status": "success", "answer": response.text}
    except Exception as err:
        raise HTTPException(status_code=500, detail=f"AI Service Error: {str(err)}")

# --- Serving Static Build ---
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DIST_DIR = os.path.join(BASE_DIR, "..", "frontend", "dist")

# Mount assets directory generated by `npm run build`
assets_dir = os.path.join(DIST_DIR, "assets")
if os.path.exists(assets_dir):
    app.mount("/assets", StaticFiles(directory=assets_dir), name="assets")

@app.get("/{full_path:path}")
def serve_spa(full_path: str):
    if full_path.startswith("api/"):
        raise HTTPException(status_code=404, detail="API route not found")

    index_path = os.path.join(DIST_DIR, "index.html")
    if os.path.exists(index_path):
        return FileResponse(index_path)
    
    return {
        "error": "Frontend build not found.",
        "solution": "Run 'npm run build' inside your frontend directory to generate frontend/dist/index.html."
    }
